sudo: required
language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 9999999

script:
  - ./mvnw clean package

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  skip_cleanup: true
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
  on:
    branch: development